import type { Metadata } from "next";
import ClientLayout from "./ClientLayout";
import DarkModeSetter from "./DarkModeSetter";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ...existing code...
  return (
    <html
      lang="en"
      className={`h-full antialiased dark`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-black">
        {/* Set dark mode on mount (client only) */}
        <DarkModeSetter />
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}




